version: "3.8"

services:
  autoheal:
      restart: always
      image: willfarrell/autoheal
      container_name: autoheal
      environment:
        - AUTOHEAL_CONTAINER_LABEL=all
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  fastapi:
    image: fastapi-healthcheck
    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
    ports:
      # - "8000:8000"
      - target: 8000
        published: 8000
        mode: host
    # restart: on-failure
