[package]
name = "fibonacci_module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/fibonacci_module.rs"

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module"] }
